# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # This step uses the actions/checkout action to download a copy of your repository on the runner
    - uses: actions/checkout@v3

    # This step uses the actions/setup-node action to set up Node.js for each version indeicated by the matrix.node-version key above
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # This step runs npm ci to install any dependencies listed your package.json file.
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test