name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'yarn'
        
    - name: Install npm dependencies
      run: yarn --frozen-lockfile

    - name: Run build task
      run: yarn build

    # Permission denied
    # - name: Create folder
    #   run: |
    #     mkdir -p /var/app/learning_github_action

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          # SOURCE: "."
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_PORT: ${{ secrets.PORT }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/var/app/learning_github_action"
          # TARGET: secrets.REMOTE_TARGET
          # EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_AFTER: |
            node dist/main.js